{ pkgs, ... }: { 
    environment.systemPackages = with pkgs; [
            hyprlock
            transmission_4-gtk
            swww
            waybar
            alacritty
            rofi-wayland
            mpv
            firefox
            file-roller
            home-manager
            nemo
            git
            libnotify
            mako
            fastfetch 
            hypridle 
            python3 
            qemu_kvm
            OVMFFull
            cbonsai
            sway-audio-idle-inhibit
            cmatrix
            btop
            cmus
            grim
            slurp
            ranger
            rofi-emoji-wayland
            cliphist
            wl-clipboard
            keepassxc
            pipes
            playerctl
            libstatgrab
            libsForQt5.qt5.qtgraphicaleffects
            figlet            
            nix-prefetch-git
            xfce.tumbler
            tty-clock
            obs-studio
            imv
            imagemagick
            ueberzugpp
            brightnessctl
            rofi-power-menu
            wget
            zathura
            gnupg
        ];
}
